name: flowinquiry
services:
  back-end:
    image: flowinquiry/flowinquiry-server:1.2.0
    volumes:
      - ./volumes/storage/:/storage
    environment:
      - JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/flowinquiry
      - SPRING_DATASOURCE_USERNAME=flowinquiry
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgresql
    env_file:
      - ./.backend.env
  front-end:
    image: flowinquiry/flowinquiry-frontend:1.2.0
    environment:
      - HOSTNAME=0.0.0.0
      # For browser access
      - NEXT_PUBLIC_BASE_URL=http://localhost:1234
      # This is the critical variable used in next.config.mjs
      - BACK_END_URL=http://back-end:8080
    env_file:
      - ./.frontend.env
    ports:
      - '0.0.0.0:1234:3000'
  postgresql:
    image: postgres:16.3
    volumes:
      - ./volumes/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=flowinquiry
      - POSTGRES_USER=flowinquiry
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}' ]
      interval: 5s
      timeout: 5s
      retries: 10
    env_file:
      - ./.backend.env