[versions]
jacoco = "0.8.12"

[libraries]
jhipster-framework = { module = "tech.jhipster:jhipster-framework", version = "8.6.0" }
springdoc-openapi-starter-webmvc-api = { module = "org.springdoc:springdoc-openapi-starter-webmvc-api", version = "2.6.0" }

[plugins]
spring-boot = { id = "org.springframework.boot", version = "3.3.4" }
openapi = {id="org.springdoc.openapi-gradle-plugin", version="1.9.0"}
