apiVersion: v1
kind: Secret
metadata:
  name: flowinquiry-secret
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgresql.user | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgresql.password | quote }}
