name: FlowInquiry CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'apps/backend/**'
            frontend:
              - 'apps/frontend/**'
            docs:
              - 'apps/docs/**'

  backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Unit and Integration Tests
        run: |
          ./gradlew :apps:backend:server:test
          ./gradlew :apps:backend:server:integrationTest
          ./gradlew :apps:backend:server:jacocoTestReport

      - name: Generate Coverage Report Summary
        uses: danielpalme/ReportGenerator-GitHub-Action@5.4.7
        with:
          reports: apps/backend/server/build/reports/jacoco/test/jacocoTestReport.xml
          targetdir: coveragereport
          reporttypes: MarkdownDeltaSummary
          historydir: hist

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport
          path: coveragereport
      - name: Show contents of coverage report folder
        run: ls -la coveragereport

      - name: Add comment to PR
        if: github.event_name == 'pull_request'
        run: gh pr comment ${{ github.event.pull_request.number }} --body-file coveragereport/MarkdownSummaryGithub.md
        env:
          GH_TOKEN: ${{ secrets.GH_PR_COMMENT_PAT }}

      - name: Publish coverage in build summary
        run: cat coveragereport/MarkdownSummaryGithub.md >> $GITHUB_STEP_SUMMARY
        shell: bash

  frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - name: Build the application
        working-directory: apps/frontend
        env:
          BACK_END_URL: "http://localhost:8080"
        run: pnpm build

  docs:
    needs: detect-changes
    if: needs.detect-changes.outputs.docs == 'true'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Clean .next folder
        run: rm -rf .next out
        working-directory: apps/docs
      - name: Build with Next.js
        run: pnpm next build
        working-directory: apps/docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/docs/out
  e2e-tests:
    needs: [ detect-changes ]
    if: needs.detect-changes.outputs.backend == 'true' || needs.detect-changes.outputs.frontend == 'true'
    uses: ./.github/workflows/playwright.yml
    secrets:
      pr_comment_pat: ${{ secrets.GH_PR_COMMENT_PAT }}


